language: python
python:
  - "2.6"
  - "2.7"
script: ./runtests.sh
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - if [[ $DJANGO_VERSION = "1.3.7" ]]; then pip install django-override-settings; fi
  - python setup.py -q install
